## Практическое задание №1.6.2

Источник данных: https://www.kaggle.com/c/house-prices-advanced-regressiontechniques

Набор данных house_price.csv содержит характеристики домов и цену
продажи ($).
Задача: построить модель, которая по числовым характеристикам жилья
предскажет его цену.

Для построения модели используйте LassoCV (https://scikitlearn.org/stable/modules/generated/sklearn.linear_model.LassoCV.html).
В LassoCV параметр alpha (λ) подбирается автоматически с помощью
перекрестной проверки (кросс-валидации). Список значений для alpha можно
задать явно используя параметр alphas. С помощью параметра cv
устанавливают количество блоков для k-блочной перекрестной проверки.
Атрибут alpha_ возвращает значение alpha, выбранное с помощью
перекрестной проверки, coef_ возвращает коэффициенты модели, а
intercept_ возвращает сдвиг. Метод score возвращает коэффициент
детерминации. Другие параметры, атрибуты и методы см. в документации).
Замечание. Параметры в классах Sklearn – это гиперпараметры, т.е.
параметры, которые мы задаем при создании экземпляра класса!

In [21]:
import pandas as pd

df = pd.read_csv('house_price.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,Unnamed: 81
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2008,WD,Normal,208500,NaN
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,NaN,NaN,NaN,0,5,2007,WD,Normal,181500,NaN
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,9,2008,WD,Normal,223500,NaN
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000,NaN
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,NaN,NaN,NaN,0,12,2008,WD,Normal,250000,NaN

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 82 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
 81  Unnamed: 81    0 non-null      float64
dtypes: float64(4), int64(35), object(43)
memory usage: 935.4+ KB

3. Для выполнения задания в наборе данных необходимо оставить только
числовые признаки. Для этого можно использовать следующий программный
код (а можно придумать свой):

In [23]:
df_numeric = df.select_dtypes(include=['int64', 'float64'])
df_numeric

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,Unnamed: 81
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,61,0,0,0,0,0,2,2008,208500,NaN
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,0,0,0,5,2007,181500,NaN
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,42,0,0,0,0,0,9,2008,223500,NaN
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,35,272,0,0,0,0,2,2006,140000,NaN
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,84,0,0,0,0,0,12,2008,250000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,40,0,0,0,0,0,8,2007,175000,NaN
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,0,0,0,2,2010,210000,NaN
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,60,0,0,0,0,2500,5,2010,266500,NaN
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,112,0,0,0,0,4,2010,142125,NaN
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,68,0,0,0,0,0,6,2008,147500,NaN

4. Удалите столбец Id и пропущенные значения.

In [24]:
df_numeric = df_numeric.drop(columns='Id')
df_numeric

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice,Unnamed: 81
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,61,0,0,0,0,0,2,2008,208500,NaN
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,0,0,0,0,0,0,5,2007,181500,NaN
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,42,0,0,0,0,0,9,2008,223500,NaN
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,35,272,0,0,0,0,2,2006,140000,NaN
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,84,0,0,0,0,0,12,2008,250000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,40,0,0,0,0,0,8,2007,175000,NaN
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,0,0,0,0,0,0,2,2010,210000,NaN
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,60,0,0,0,0,2500,5,2010,266500,NaN
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,0,112,0,0,0,0,4,2010,142125,NaN
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,68,0,0,0,0,0,6,2008,147500,NaN

In [27]:
df_numeric.isna().sum()

MSSubClass          0
LotFrontage       259
LotArea             0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
MasVnrArea          8
BsmtFinSF1          0
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
TotRmsAbvGrd        0
Fireplaces          0
GarageYrBlt        81
GarageCars          0
GarageArea          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
MiscVal             0
MoSold              0
YrSold              0
SalePrice           0
Unnamed: 81      1460
dtype: int64

In [30]:
df_numeric['LotFrontage'] = df_numeric['LotFrontage'].fillna(df_numeric['LotFrontage'].median())
df_numeric['MasVnrArea'] = df_numeric['MasVnrArea'].fillna(0)
df_numeric['GarageYrBlt'] = df_numeric['GarageYrBlt'].fillna(df_numeric['YearBuilt'])
df_numeric

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,0,61,0,0,0,0,0,2,2008,208500
1,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,298,0,0,0,0,0,0,5,2007,181500
2,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,0,42,0,0,0,0,0,9,2008,223500
3,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,0,35,272,0,0,0,0,2,2006,140000
4,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,192,84,0,0,0,0,0,12,2008,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,60,62.0,7917,6,5,1999,2000,0.0,0,0,...,0,40,0,0,0,0,0,8,2007,175000
1456,20,85.0,13175,6,6,1978,1988,119.0,790,163,...,349,0,0,0,0,0,0,2,2010,210000
1457,70,66.0,9042,7,9,1941,2006,0.0,275,0,...,0,60,0,0,0,0,2500,5,2010,266500
1458,20,68.0,9717,5,6,1950,1996,0.0,49,1029,...,366,0,112,0,0,0,0,4,2010,142125
1459,20,75.0,9937,5,6,1965,1965,0.0,830,290,...,736,68,0,0,0,0,0,6,2008,147500

In [38]:
df = df_numeric.dropna()
df

5. Разделите набор данных на входные данные X (все столбцы кроме SalePrice)
и ответы y (столбец SalePrice).

In [37]:
X = df_numeric.drop('SalePrice', axis=1)
y = df_numeric['SalePrice']

      MSSubClass  LotFrontage  LotArea  OverallQual  OverallCond  YearBuilt  \
0             60         65.0     8450            7            5       2003
1             20         80.0     9600            6            8       1976
2             60         68.0    11250            7            5       2001
3             70         60.0     9550            7            5       1915
4             60         84.0    14260            8            5       2000
...          ...          ...      ...          ...          ...        ...
1455          60         62.0     7917            6            5       1999
1456          20         85.0    13175            6            6       1978
1457          70         66.0     9042            7            9       1941
1458          20         68.0     9717            5            6       1950
1459          20         75.0     9937            5            6       1965

      YearRemodAdd  MasVnrArea  BsmtFinSF1  BsmtFinSF2  ...  GarageArea  \
0             2003       196.0         706           0  ...         548
1             1976         0.0         978           0  ...         460
2             2002       162.0         486           0  ...         608
3             1970         0.0         216           0  ...         642
4             2000       350.0         655           0  ...         836
...            ...         ...         ...         ...  ...         ...
1455          2000         0.0           0           0  ...         460
1456          1988       119.0         790         163  ...         500
1457          2006         0.0         275           0  ...         252
1458          1996         0.0          49        1029  ...         240
1459          1965         0.0         830         290  ...         276

      WoodDeckSF  OpenPorchSF  EnclosedPorch  3SsnPorch  ScreenPorch  \
0              0           61              0          0            0
1            298            0              0          0            0
2              0           42              0          0            0
3              0           35            272          0            0
4            192           84              0          0            0
...          ...          ...            ...        ...          ...
1455           0           40              0          0            0
1456         349            0              0          0            0
1457           0           60              0          0            0
1458         366            0            112          0            0
1459         736           68              0          0            0

      PoolArea  MiscVal  MoSold  YrSold
0            0        0       2    2008
1            0        0       5    2007
2            0        0       9    2008
3            0        0       2    2006
4            0        0      12    2008
...        ...      ...     ...     ...
1455         0        0       8    2007
1456         0        0       2    2010
1457         0     2500       5    2010
1458         0        0       4    2010
1459         0        0       6    2008

[1460 rows x 36 columns]
0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

6. Разделите данные на обучающую и тестовую выборки.

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

7. Обучите модель LassoCV (установите значение гиперпараметра cv
самостоятельно). Оцените качество полученной модели. Посмотрите на
коэффициенты модели. Есть ли коэффициенты равные 0? Что это означает?
Сделайте выводы.

In [34]:
from sklearn.linear_model import LassoCV
lasso = LassoCV(cv=5) # Для примера возьмем cv = 5 Это означает, что для подбора alpha будет использоваться 5-блочная перекрестная проверка.
lasso.fit(X_train, y_train) # Обучаем
lasso.score(X_test, y_test) # Оцениваем качество
lasso.coef_ # Значения коэффициентов

array([-0.00000000e+00, -0.00000000e+00,  3.14283599e-01,  0.00000000e+00,
        0.00000000e+00,  3.53545014e+02,  6.09434726e+01,  2.91385566e+01,
        1.01909837e+01, -0.00000000e+00,  0.00000000e+00,  2.61900123e+01,
        0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  6.30468586e+01,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  7.25829491e+01,  2.92898013e+01,
        0.00000000e+00, -0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00, -3.82570387e+00,  0.00000000e+00,  0.00000000e+00])

In [36]:
important_features = X.columns[lasso.coef_ != 0]
print(important_features)

Index(['LotArea', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'TotalBsmtSF', 'GrLivArea', 'GarageArea', 'WoodDeckSF', 'MiscVal'],
      dtype='object')