## Практическое задание

В файле water.txt представлено 61 наблюдение. Каждое наблюдение – город в
Англии и Уэльсе. Города дополнительно поделены на северные и южные. Для
каждого города известны средняя годовая смертность на 100000 населения (по
данным 1958–1964) и концентрация кальция в питьевой воде (в частях на
миллион). Чем выше концентрация кальция, тем жёстче вода.

In [5]:
import pandas as pd

df = pd.read_csv('14water.txt', sep = '\t')
print(df.head())

  location        tow  mortalit  hardness
0     Sout        Bat       124       105
1     Nort  Birkenhea       166        17
2     Sout  Birmingha       146         5
3     Nort   Blackbur       180        14
4     Nort   Blackpoo       160        18

In [8]:
df.loc[df.location == 'Sout'].describe()

         mortalit    hardness
count   26.000000   26.000000
mean   137.076923   69.769231
std     14.053962   40.360682
min    109.000000    5.000000
25%    125.250000   40.250000
50%    135.500000   75.500000
75%    148.000000   99.750000
max    162.000000  138.000000

In [9]:
df.loc[df.location == 'Nort'].describe()

         mortalit   hardness
count   35.000000  35.000000
mean   162.857143  30.400000
std     13.760863  26.134494
min    137.000000   6.000000
25%    155.000000  12.500000
50%    163.000000  17.000000
75%    171.500000  44.000000
max    198.000000  94.000000

2) Постройте 95% доверительные интервалы для средней годовой смертности по
всем южным и северным городам. Отличаются ли границы интервалов?

In [27]:
from statsmodels.stats.weightstats import _tconfint_generic
import numpy as np

south = df[df['location'] == 'Sout']['mortalit']
south_mean = south.mean()
south_std = south.std() / np.sqrt(south.shape[0])
print('95% interval south:', _tconfint_generic(south_mean, south_std, south.shape[0] - 1, 0.005, 'two-sided'))

north = df[df['location'] == 'Nort']['mortalit']
north_mean = north.mean()
north_std = north.std() / np.sqrt(north.shape[0])
print('95% interval north:', _tconfint_generic(north_mean, north_std, north.shape[0] - 1, 0.005, 'two-sided'))

95% interval south: (np.float64(128.5927629476033), np.float64(145.56108320624284))
95% interval north: (np.float64(155.87456702417697), np.float64(169.83971869010875))

Средняя годовая смертность в северных городах статистически значимо выше, чем в южных.

Постройте 95% доверительные интервалы для средней концентрации кальция в
питьевой воде для южных и северных городов. Отличаются ли границы
интервалов?

In [28]:
south = df[df['location'] == 'Sout']['hardness']
south_mean = south.mean()
south_std = south.std() / np.sqrt(south.shape[0])
print('95% interval south:', _tconfint_generic(south_mean, south_std, south.shape[0] - 1, 0.005, 'two-sided'))

north = df[df['location'] == 'Nort']['hardness']
north_mean = north.mean()
north_std = north.std() / np.sqrt(north.shape[0])
print('95% interval north:', _tconfint_generic(north_mean, north_std, north.shape[0] - 1, 0.005, 'two-sided'))

95% interval south: (np.float64(45.40410962178791), np.float64(94.13435191667364))
95% interval north: (np.float64(17.138761406707864), np.float64(43.66123859329213))

Концентрация кальция в питьевой воде статистически значимо выше в южных городах, чем в северных.

В результате анализа установлено, что средняя годовая смертность статистически значимо выше в северных городах, чем в южных. Одновременно с этим концентрация кальция в питьевой воде статистически значимо выше в южных городах. Это позволяет сделать вывод о наличии обратной связи между уровнем смертности и жёсткостью воды: более высокая концентрация кальция ассоциируется с более низкой смертностью.